### ISSUE TITLE
Not possible to act when an action is done

### ISSUE THREAD

**Issue by CharlonTank** [nunntom/elm-ui-select#1]
Hello, is there a way to trigger something when onLoseFocus?

I tried using Select.view [ Element.onLoseFocus OnLoseFocus] but it doesn't work.

Since Select Msgs are internal, I cannot pattern match on subMsg in my update function.

Also I want to trigger something directly when an element is selected.

**Comment by nunntom** [comment]
Hi @CharlonTank 

I have been thinking about a nice api to hook into these kinds of events but haven't settled on anything yet. Ideas are welcome.

One way to achieve both of these currently is to compare `Select.toValue`/`Select.isFocused` from before and after `Select.update` to see if they have changed and how. Note that `Select.isFocused` is added in version 2.1.0.

Tom

**Comment by CharlonTank** [comment]
Hey :) Thank you for your answer.

What is the purpose of not exposing the different Msgs?

**Comment by nunntom** [comment]
Do let me know if the answer solved your problem in your particular use case.

> What is the purpose of not exposing the different Msgs?

Generally by hiding implementation and exposing only a limited api it allows me to make changes to the internal implementation without breaking the public api. If I expose the Msg constructors they become part of the public api and I'd have to bump a major version every time I add or change one of them even slightly.

**Comment by CharlonTank** [comment]
I understand.
Yes I use Select.toValue to compare old and new values.
Thank you.

I know it's not related to this problem and it would be better to talk in another place about it but do you have a way to shrink the height of the select? I feel like it's impossible to make it shorter. I have some elm-ui inputs and selects but my selects take too much room:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/4601603/198328703-36f17fb6-92e5-444e-80f9-10c3251cd867.png">
Do you have a place like discord or slack to talk about your nice select :)?

**Comment by nunntom** [comment]
You should be able to provide `Element.Attribute`s to the select to control the height but it's hard to tell from the screenshot what is causing the height in this case, whether padding, alignment or height etc.

You can find me on Elm slack Tom N.

**Comment by CharlonTank** [comment]
I don't know why I had this problem and could not fix it before.
Just adding height to Select.view fixed the problem.

Thank you!

**Comment by nunntom** [comment]
> Hello, is there a way to trigger something when onLoseFocus?
> 
> I tried using Select.view [ Element.onLoseFocus OnLoseFocus] but it doesn't work.
> 
> Since Select Msgs are internal, I cannot pattern match on subMsg in my update function.
> 
> Also I want to trigger something directly when an element is selected.

Just to note from 3.0.0 it is now possible to trigger your own msg on focus, blur, input and when the selected item changes. See docs for [updateWith](https://package.elm-lang.org/packages/nunntom/elm-ui-select/latest/Select#updateWith).

@CharlonTank

**Comment by CharlonTank** [comment]
That's awesome thank you! So cool! I already updated to 3.0.0 yesterday and will certainly change to this soon!
